spring.datasource.url=jdbc:postgresql://localhost:5432/jira_lite
spring.datasource.username=postgres
spring.datasource.password=frostbjorne
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.studying.webservice.configurations.SchemaTenantIdentifierResolver
spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.studying.webservice.configurations.SchemaMultiTenantConnectionProvider

spring.liquibase.enabled=false
jwt.secret=uAp39r6WvLzQxJ9bMkT3U8kZy2NH4sX1aCg7VeFi0LM=


