# DB
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/jira_lite
spring.datasource.username = postgres
spring.datasource.password = frostbjorne
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


## Only for dev process
spring.jpa.hibernate.ddl-auto=update

# Spring Data
spring.data.rest.base-path=/api
spring.data.rest.detection-strategy=ANNOTATED

# Spring Jpa
spring.jpa.open-in-view=false

# Frontend
allowed.origins=http://localhost:4200

